### ISSUE TITLE
Figuras en eps

### ISSUE THREAD

**Issue by forero** [Fernandez-Trincado/Bullet_Groups-2014#1]
No estan las figuras en formato eps dentro del repositorio.

**Comment by Fernandez-Trincado** [comment]
Ok, ya las cambio, las tengo en mi computador.

On Thu, Feb 27, 2014 at 8:23 AM, Jaime Forero-Romero <
notifications@github.com> wrote:

> No estan las figuras en formato eps dentro del repositorio.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Fernandez-Trincado/Bullet_Groups-2014/issues/1
> .

## 

---

José Gregorio Fernández Trincado
Repositories: https://github.com/Fernandez-Trincado
Mail: jfernandez@cida.ve, jfernandezt87@gmail.com mevans@dfa.uv.cl

**Comment by forero** [comment]
Ahora las figuras producen un error

LaTeX Error: Cannot determine size of graphic in Figures_eps/figure_7_1.eps (
no BoundingBox)

como produces esos .eps?

**Comment by Fernandez-Trincado** [comment]
Listo puede probar con el nuevo directorio que acabo de colocar?.

Las genero con: sam2p nombre.png EPS:nombre.eps

On Thu, Feb 27, 2014 at 8:50 AM, Jaime Forero-Romero <
notifications@github.com> wrote:

> Ahora las figuras producen un error
> 
> LaTeX Error: Cannot determine size of graphic in
> Figures_eps/figure_7_1.eps (
> no BoundingBox)
> 
> como produces esos .eps?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Fernandez-Trincado/Bullet_Groups-2014/issues/1#issuecomment-36243021
> .

## 

---

José Gregorio Fernández Trincado
Repositories: https://github.com/Fernandez-Trincado
Mail: jfernandez@cida.ve, jfernandezt87@gmail.com mevans@dfa.uv.cl

**Comment by forero** [comment]
Funcionan. Pero la imagen es de mala calidad. Yo recomendaria que las guardaras directamente como eps dentro de tu codigo de python.

**Comment by Fernandez-Trincado** [comment]
ok

2014-02-27 9:12 GMT-05:00 Jaime Forero-Romero notifications@github.com:

> Funcionan. Pero la imagen es de mala calidad. Yo recomendaria que las
> guardaras directamente como eps dentro de tu codigo de python.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Fernandez-Trincado/Bullet_Groups-2014/issues/1#issuecomment-36245070
> .

## 

---

José Gregorio Fernández Trincado
Repositories: https://github.com/Fernandez-Trincado
Mail: jfernandez@cida.ve, jfernandezt87@gmail.com mevans@dfa.uv.cl
